export const weatherConstants = {
    TEMPERATURE: 'Temperature',
    FAHRENHEIT: 'F',
    PASCAL: 'hPa',
    SUNRISE: 'Sunrise',
    SUNSET: 'Sunset',
    SEA_LEVEL: 'Sea Level',
    FORECAST_5_Day: '5 day Forecast',
    NO_CITIES_FOUND: 'No Cities Found',
    LOADING: 'Loading...',
    CURRENT_WEATHER_DESC: ['Below cards contains first 5 european cities weather info, laid within definite circle that is specified by center point with', '55.5 latitude', 'and', '37.5 longitude', 'on', ],
    BACK_TO_CITIES: 'Back To All Cities',
    FORECAST_WEATHER_DESC: ['Below is 5 day forecast for', 'at', '9:00:00 AM'],
    NO_FORECAST_DATA: 'No Forecast Data Found',
    PAGE_NOT_FOUND: 'Page Not Found',
}